### ISSUE TITLE
Site not reporting correct data on 4/8/2016

### ISSUE THREAD

**Issue by thenewwazoo** [tedski/isthereagiantsgametoday#1]
**Description:**
The site reports "No" on 4/8/2016, but there are confirmed reports of Giants fans on public transit.

**Expected behaviour:**
The site should report "Yes", as those Giants fans are undoubtedly being dicks.

**Steps to reproduce:**
1) Set date to 4/8/2016.
2) Be on public transit.
3) Observe Giants fans being dicks.
4) Open website, and observe "No" is reported.

**Comment by tedski** [comment]
Works on my box.
